#include <odin/window/Keyboard.hpp>

#define ODIN_KC_CASE(code) case code: return #code

namespace odin
{
	std::string Keyboard::interpretKeyCode(Keyboard::Key code)
	{
		switch (code)
		{
			ODIN_KC_CASE(Key::Backspace);
			ODIN_KC_CASE(Key::Tab);
			ODIN_KC_CASE(Key::Clear);
			ODIN_KC_CASE(Key::Enter);
			ODIN_KC_CASE(Key::Pause);
			ODIN_KC_CASE(Key::CapsLock);
			ODIN_KC_CASE(Key::Escape);
			ODIN_KC_CASE(Key::Space);
			ODIN_KC_CASE(Key::PageUp);
			ODIN_KC_CASE(Key::PageDown);
			ODIN_KC_CASE(Key::End);
			ODIN_KC_CASE(Key::Home);
			ODIN_KC_CASE(Key::LeftArrow);
			ODIN_KC_CASE(Key::UpArrow);
			ODIN_KC_CASE(Key::RightArrow);
			ODIN_KC_CASE(Key::DownArrow);
			ODIN_KC_CASE(Key::Select);
			ODIN_KC_CASE(Key::Print);
			ODIN_KC_CASE(Key::Execute);
			ODIN_KC_CASE(Key::PrintScreen);
			ODIN_KC_CASE(Key::Insert);
			ODIN_KC_CASE(Key::Delete);
			ODIN_KC_CASE(Key::Help);
			ODIN_KC_CASE(Key::A);
			ODIN_KC_CASE(Key::B);
			ODIN_KC_CASE(Key::C);
			ODIN_KC_CASE(Key::D);
			ODIN_KC_CASE(Key::E);
			ODIN_KC_CASE(Key::F);
			ODIN_KC_CASE(Key::G);
			ODIN_KC_CASE(Key::H);
			ODIN_KC_CASE(Key::I);
			ODIN_KC_CASE(Key::J);
			ODIN_KC_CASE(Key::K);
			ODIN_KC_CASE(Key::L);
			ODIN_KC_CASE(Key::M);
			ODIN_KC_CASE(Key::N);
			ODIN_KC_CASE(Key::O);
			ODIN_KC_CASE(Key::P);
			ODIN_KC_CASE(Key::Q);
			ODIN_KC_CASE(Key::R);
			ODIN_KC_CASE(Key::S);
			ODIN_KC_CASE(Key::T);
			ODIN_KC_CASE(Key::U);
			ODIN_KC_CASE(Key::V);
			ODIN_KC_CASE(Key::W);
			ODIN_KC_CASE(Key::X);
			ODIN_KC_CASE(Key::Y);
			ODIN_KC_CASE(Key::Z);
			ODIN_KC_CASE(Key::LeftSystem);
			ODIN_KC_CASE(Key::RightSystem);
			ODIN_KC_CASE(Key::Application);
			ODIN_KC_CASE(Key::Num0);
			ODIN_KC_CASE(Key::Num1);
			ODIN_KC_CASE(Key::Num2);
			ODIN_KC_CASE(Key::Num3);
			ODIN_KC_CASE(Key::Num4);
			ODIN_KC_CASE(Key::Num5);
			ODIN_KC_CASE(Key::Num6);
			ODIN_KC_CASE(Key::Num7);
			ODIN_KC_CASE(Key::Num8);
			ODIN_KC_CASE(Key::Num9);
			ODIN_KC_CASE(Key::Numpad0);
			ODIN_KC_CASE(Key::Numpad1);
			ODIN_KC_CASE(Key::Numpad2);
			ODIN_KC_CASE(Key::Numpad3);
			ODIN_KC_CASE(Key::Numpad4);
			ODIN_KC_CASE(Key::Numpad5);
			ODIN_KC_CASE(Key::Numpad6);
			ODIN_KC_CASE(Key::Numpad7);
			ODIN_KC_CASE(Key::Numpad8);
			ODIN_KC_CASE(Key::Numpad9);
			ODIN_KC_CASE(Key::Multiply);
			ODIN_KC_CASE(Key::Add);
			ODIN_KC_CASE(Key::Separator);
			ODIN_KC_CASE(Key::Substract);
			ODIN_KC_CASE(Key::Decimal);
			ODIN_KC_CASE(Key::Divide);
			ODIN_KC_CASE(Key::F1);
			ODIN_KC_CASE(Key::F2);
			ODIN_KC_CASE(Key::F3);
			ODIN_KC_CASE(Key::F4);
			ODIN_KC_CASE(Key::F5);
			ODIN_KC_CASE(Key::F6);
			ODIN_KC_CASE(Key::F7);
			ODIN_KC_CASE(Key::F8);
			ODIN_KC_CASE(Key::F9);
			ODIN_KC_CASE(Key::F10);
			ODIN_KC_CASE(Key::F11);
			ODIN_KC_CASE(Key::F12);
			ODIN_KC_CASE(Key::F13);
			ODIN_KC_CASE(Key::F14);
			ODIN_KC_CASE(Key::F15);
			ODIN_KC_CASE(Key::F16);
			ODIN_KC_CASE(Key::F17);
			ODIN_KC_CASE(Key::F18);
			ODIN_KC_CASE(Key::F19);
			ODIN_KC_CASE(Key::F20);
			ODIN_KC_CASE(Key::F21);
			ODIN_KC_CASE(Key::F22);
			ODIN_KC_CASE(Key::F23);
			ODIN_KC_CASE(Key::F24);
			ODIN_KC_CASE(Key::NumLock);
			ODIN_KC_CASE(Key::ScrollLock);
			ODIN_KC_CASE(Key::LeftShift);
			ODIN_KC_CASE(Key::RightShift);
			ODIN_KC_CASE(Key::LeftCtrl);
			ODIN_KC_CASE(Key::RightCtrl);
			ODIN_KC_CASE(Key::LeftAlt);
			ODIN_KC_CASE(Key::RightAlt);
			ODIN_KC_CASE(Key::LeftBracket);
			ODIN_KC_CASE(Key::RightBracket);
			ODIN_KC_CASE(Key::Semicolon);
			ODIN_KC_CASE(Key::Comma);
			ODIN_KC_CASE(Key::Period);
			ODIN_KC_CASE(Key::Quote);
			ODIN_KC_CASE(Key::Slash);
			ODIN_KC_CASE(Key::Backslash);
			ODIN_KC_CASE(Key::Tilde);
			ODIN_KC_CASE(Key::Equal);
			ODIN_KC_CASE(Key::Hyphen);
		}
		return "Undefined " + std::to_string((int)code);
	}

}